repos:
-   repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      pass_filenames: true
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
    -   id: mypy
        args: [--config-file, pyproject.toml]
        additional_dependencies: [numpy]
